version: '2.0'

services:
  web:
    image: ruby:2.3
    command: rails server -b 0.0.0.0 -p 80
    environment:
      RAILS_ENV:
      DATABASE_HOST: db
      SETTINGS__SMTP__ADDRESS: smtp.mandrillapp.com
      SETTINGS__SMTP__DOMAIN: domain
      SETTINGS__SMTP__USER_NAME: email
      SETTINGS__SMTP__PASSWORD: api-key
      SETTINGS__SMTP__HOST: localhost:3000
      SETTINGS__SMTP__DEFAULT_FROM: notifications@example.org
      DEVISE_EMAIL: notifications@example.org
      DEVISE_CONFIRMABLE: 'true'
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tmpfs: /app/tmp
    depends_on:
      - db
    ports:
      - 80:80

  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  bundle:
