version: '2.0'

services:
  web:
    command: rails server
    image: ruby:2.3
    environment:
      RAILS_ENV:
      DATABASE_HOST: 'db'
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tmpfs: /app/tmp
    depends_on:
      - db
    ports:
      - 3001:3000

  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  bundle:
