version: '2.0'

services:
  smtp:
    image: 'djfarrelly/maildev:latest'
    command: 'bin/maildev --web 3080 --smtp 1025 --incoming-user smtp --incoming-pass smtp'
    ports:
      - '3080:3080'

  web:
    image: ruby:2.3
    command: rails server -b 0.0.0.0 -p 80
    environment:
      RAILS_ENV:
      DATABASE_HOST: db
      DEVISE_EMAIL: notifications@ilabsea.org
      DEVISE_CONFIRMABLE: 'true'
      SETTINGS__SMTP__ADDRESS: smtp
      SETTINGS__SMTP__DOMAIN: domain
      SETTINGS__SMTP__USER_NAME: smtp
      SETTINGS__SMTP__PASSWORD: smtp
      SETTINGS__SMTP__PORT: 1025
      SETTINGS__SMTP__HOST: localhost:3000
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tmpfs: /app/tmp
    depends_on:
      - db
      - smtp
    ports:
      - 80:80

  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  bundle:
