development:
  adapter: mysql2
  encoding: utf8
  database: guisso_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: guisso_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: guisso
  pool: 5
  username: root
  password:
